version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: remake-2-server-mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: remake2
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
